#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/../../../../vendor/autoload.php');
require(__DIR__ . '/../../../../vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/FormatData.php');
require(__DIR__ . '/FormatXml.php');
require(__DIR__ . '/../models/Data.php');
require(__DIR__ . '/../models/Layer.php');
require(__DIR__ . '/../models/LayDat.php');

$dsn = false;
$tablePrefix = false;
$username = false;
$password = false;
$param = false;
$action = false;

foreach ($argv as $a)
{
	if (strpos($a,"-dsn=") !== false)
	{
		$dsn = str_replace("-dsn=","",$a);
	}	
	
	if (strpos($a,"-tablePrefix=") !== false)
	{
		$tablePrefix = str_replace("-tablePrefix=","",$a);
	}
	
	if (strpos($a,"-username=") !== false)
	{
		$username = str_replace("-username=","",$a);
	}
	
	if (strpos($a,"-password=") !== false)
	{
		$password = str_replace("-password=","",$a);
	}
	
	if (strpos($a,"-param=") !== false)
	{
		$param = str_replace("-param=","",$a);
	}
	
	if (strpos($a,"-action=") !== false)
	{
		$action = str_replace("-action=","",$a);
	}
		
}

if (!empty($dsn) && !empty($username)&& !empty($password) && !empty($param) && $action == 'import')
{		
	$format = new \amilna\iyo\components\FormatData($dsn,$tablePrefix,$username,$password,$param);
	$exitCode = $format->import();			
	exit($exitCode);
}
elseif (!empty($dsn) && !empty($username)&& !empty($password) && !empty($param) && $action == 'getXml')
{		
	$format = new \amilna\iyo\components\FormatXml($dsn,$tablePrefix,$username,$password,$param);
	$exitCode = $format->printXml();			
	exit($exitCode);
}
elseif (!empty($dsn) && !empty($username)&& !empty($password) && !empty($param) && $action == 'clearTile')
{		
	$format = new \amilna\iyo\components\FormatTile($dsn,$tablePrefix,$username,$password,$param);
	$exitCode = $format->clearTile();			
	exit($exitCode);
}
